/**
 * nav bar
 */
export const NAV_BAR = {
  NAV_BAR_ACTION: 'NAV_BAR_ACTION',
};

export const LOGIN = {
  LOGIN_REQUEST: 'LOGIN/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN/LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN/LOGIN_ERROR',
};
