/**
 * nav bar
 */
export const NAV_BAR = {
  NAV_BAR_ACTION: 'NAV_BAR_ACTION',
};

export const LOGIN = {
  LOGIN_REQUEST: 'LOGIN/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN/LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN/LOGIN_ERROR',
  LOGOUT: 'LOGIN/LOGOUT'
};


export const USER = {
  USER_LIST_REQUEST: 'USER/USER_LIST_REQUEST',
  USER_LIST_REQUEST_SUCCESS: 'USER/USER_LIST_REQUEST_SUCCESS',
  USER_LIST_REQUEST_ERROR: 'USER/USER_LIST_REQUEST_ERROR',
};

export const CHAT_PURCHASE = {
  CHAT_PURCHASE_REQUEST: 'CHAT_PURCHASE/CHAT_PURCHASE_REQUEST',
  CHAT_PURCHASE_SUCCESS: 'CHAT_PURCHASE/CHAT_PURCHASE_SUCCESS',
  CHAT_PURCHASE_ERROR: 'CHAT_PURCHASE/CHAT_PURCHASE_ERROR'
};
